<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('sku')->unique();$t->json('attributes')->nullable();$t->decimal('price',12,2)->nullable();$t->decimal('discount_price',12,2)->nullable();$t->unsignedInteger('stock')->default(0);$t->boolean('status')->default(true);$t->timestamps();});
Schema::create('product_images',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('url');$t->string('alt')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_primary')->default(false);$t->timestamps();});
Schema::create('shipping_zones',function(Blueprint $t){$t->id();$t->string('name');$t->json('states')->nullable();$t->decimal('rate',12,2)->default(0);$t->decimal('free_shipping_minimum',12,2)->nullable();$t->unsignedInteger('estimated_days')->default(3);$t->boolean('active')->default(true);$t->timestamps();});
Schema::create('notifications',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type');$t->string('notifiable_type');$t->unsignedBigInteger('notifiable_id');$t->text('data');$t->timestamp('read_at')->nullable();$t->timestamps();$t->index(['notifiable_type','notifiable_id']);});
Schema::create('returns',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('status')->default('requested');$t->string('reason');$t->text('description')->nullable();$t->decimal('refund_amount',12,2)->default(0);$t->text('admin_note')->nullable();$t->timestamps();});
Schema::create('support_tickets',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('subject');$t->text('message');$t->string('status')->default('open');$t->string('priority')->default('normal');$t->text('admin_reply')->nullable();$t->timestamps();});
Schema::create('loyalty_accounts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->unsignedInteger('points')->default(0);$t->timestamps();});
Schema::create('referrals',function(Blueprint $t){$t->id();$t->foreignId('referrer_id')->constrained('users')->cascadeOnDelete();$t->foreignId('referred_id')->nullable()->constrained('users')->nullOnDelete();$t->string('code')->unique();$t->unsignedInteger('reward_points')->default(0);$t->timestamp('completed_at')->nullable();$t->timestamps();});
Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('auditable_type')->nullable();$t->unsignedBigInteger('auditable_id')->nullable();$t->json('metadata')->nullable();$t->ipAddress('ip_address')->nullable();$t->timestamps();$t->index(['auditable_type','auditable_id']);});
Schema::create('faqs',function(Blueprint $t){$t->id();$t->string('question');$t->text('answer');$t->unsignedInteger('sort_order')->default(0);$t->boolean('active')->default(true);$t->timestamps();});
Schema::create('abandoned_carts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('session_id')->nullable();$t->json('items');$t->timestamp('reminded_at')->nullable();$t->timestamps();});
}
public function down():void{foreach(['abandoned_carts','faqs','audit_logs','referrals','loyalty_accounts','support_tickets','returns','notifications','shipping_zones','product_images','product_variants'] as $t)Schema::dropIfExists($t);}};
