<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('products',function(Blueprint $t){$t->string('brand')->nullable();$t->json('tags')->nullable();$t->json('specifications')->nullable();$t->string('seo_title')->nullable();$t->text('seo_description')->nullable();$t->timestamp('published_at')->nullable();$t->index(['status','featured']);});
Schema::table('users',function(Blueprint $t){$t->string('permissions')->nullable();$t->boolean('two_factor_enabled')->default(false);$t->string('two_factor_secret')->nullable();$t->string('referral_code')->nullable()->unique();$t->foreignId('referred_by')->nullable()->constrained('users')->nullOnDelete();});
Schema::create('vendors',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('business_name');$t->string('slug')->unique();$t->text('description')->nullable();$t->string('status')->default('pending');$t->decimal('commission_rate',5,2)->default(10);$t->decimal('balance',12,2)->default(0);$t->string('phone')->nullable();$t->string('address')->nullable();$t->timestamps();});
Schema::table('orders',function(Blueprint $t){$t->string('tracking_number')->nullable()->index();$t->string('courier')->nullable();$t->timestamp('shipped_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->timestamp('paid_at')->nullable();});
Schema::table('order_items',function(Blueprint $t){$t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete();$t->foreignId('vendor_id')->nullable()->constrained()->nullOnDelete();});
Schema::create('shipping_rates',function(Blueprint $t){$t->id();$t->foreignId('shipping_zone_id')->constrained()->cascadeOnDelete();$t->string('courier');$t->decimal('rate',12,2);$t->unsignedInteger('min_weight')->nullable();$t->unsignedInteger('max_weight')->nullable();$t->unsignedInteger('estimated_days')->default(3);$t->boolean('active')->default(true);$t->timestamps();});
Schema::create('payment_transactions',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('provider');$t->string('reference')->unique();$t->decimal('amount',12,2);$t->string('currency',3)->default('NGN');$t->string('status')->default('pending');$t->json('payload')->nullable();$t->timestamps();$t->index(['provider','status']);});
Schema::create('refunds',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('return_id')->nullable()->constrained('returns')->nullOnDelete();$t->decimal('amount',12,2);$t->string('provider')->nullable();$t->string('reference')->nullable()->unique();$t->string('status')->default('requested');$t->text('reason')->nullable();$t->json('payload')->nullable();$t->timestamps();});
Schema::create('return_items',function(Blueprint $t){$t->id();$t->foreignId('return_id')->constrained('returns')->cascadeOnDelete();$t->foreignId('order_item_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('quantity');$t->timestamps();});
Schema::create('loyalty_transactions',function(Blueprint $t){$t->id();$t->foreignId('loyalty_account_id')->constrained()->cascadeOnDelete();$t->integer('points');$t->string('type');$t->string('reference')->nullable();$t->text('description')->nullable();$t->timestamps();});
Schema::create('promotion_campaigns',function(Blueprint $t){$t->id();$t->string('name');$t->string('type');$t->decimal('value',12,2);$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
Schema::create('gift_cards',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->decimal('initial_value',12,2);$t->decimal('balance',12,2);$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->timestamp('expires_at')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
Schema::create('gift_card_transactions',function(Blueprint $t){$t->id();$t->foreignId('gift_card_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->decimal('amount',12,2);$t->string('type');$t->timestamps();});
Schema::create('product_questions',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->text('question');$t->text('answer')->nullable();$t->boolean('approved')->default(false);$t->timestamps();});
Schema::create('product_comparisons',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('session_id')->nullable();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->timestamps();});
Schema::create('recently_viewed_products',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('session_id')->nullable();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->timestamp('viewed_at');$t->index(['session_id','viewed_at']);});
Schema::create('abandoned_cart_reminders',function(Blueprint $t){$t->id();$t->foreignId('abandoned_cart_id')->constrained()->cascadeOnDelete();$t->string('channel');$t->timestamp('sent_at');$t->timestamps();});
Schema::create('vendor_products',function(Blueprint $t){$t->id();$t->foreignId('vendor_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['vendor_id','product_id']);});
Schema::create('vendor_payouts',function(Blueprint $t){$t->id();$t->foreignId('vendor_id')->constrained()->cascadeOnDelete();$t->decimal('amount',12,2);$t->string('status')->default('requested');$t->string('reference')->unique();$t->string('bank_name')->nullable();$t->string('account_number')->nullable();$t->string('account_name')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
Schema::create('vendor_commissions',function(Blueprint $t){$t->id();$t->foreignId('vendor_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->decimal('gross',12,2);$t->decimal('commission',12,2);$t->decimal('net',12,2);$t->timestamps();});
Schema::create('disputes',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('vendor_id')->nullable()->constrained()->nullOnDelete();$t->string('subject');$t->text('description');$t->string('status')->default('open');$t->text('resolution')->nullable();$t->timestamps();});
Schema::create('vendor_ratings',function(Blueprint $t){$t->id();$t->foreignId('vendor_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('rating');$t->text('comment')->nullable();$t->boolean('approved')->default(true);$t->timestamps();});
Schema::create('api_tokens',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('token_hash')->unique();$t->timestamp('last_used_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamps();});
}
public function down():void{foreach(['api_tokens','vendor_ratings','disputes','vendor_commissions','vendor_payouts','vendor_products','abandoned_cart_reminders','recently_viewed_products','product_comparisons','product_questions','gift_card_transactions','gift_cards','promotion_campaigns','loyalty_transactions','return_items','refunds','payment_transactions','shipping_rates'] as $t)Schema::dropIfExists($t);Schema::table('order_items',function(Blueprint $t){$t->dropForeign(['variant_id']);$t->dropForeign(['vendor_id']);$t->dropColumn(['variant_id','vendor_id']);});Schema::table('orders',function(Blueprint $t){$t->dropColumn(['tracking_number','courier','shipped_at','delivered_at','cancelled_at','paid_at']);});Schema::dropIfExists('vendors');Schema::table('products',function(Blueprint $t){$t->dropColumn(['brand','tags','specifications','seo_title','seo_description','published_at']);});Schema::table('users',function(Blueprint $t){$t->dropForeign(['referred_by']);$t->dropColumn(['permissions','two_factor_enabled','two_factor_secret','referral_code','referred_by']);});}};
