<?php

namespace App\Http\Controllers;

use App\Models\{Address,Coupon,Order,Product};
use App\Services\{PaymentService,ShippingService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

class CheckoutController extends Controller
{
 private function cart(){return collect(session('cart',[]));}
 private function totals(?string $state=null){$items=$this->cart();$subtotal=(float)$items->sum(fn($i)=>$i['price']*$i['quantity']);$discount=0;if(session('coupon')){$coupon=Coupon::where('code',session('coupon'))->first();if($coupon?->validFor($subtotal))$discount=$coupon->discount($subtotal);else session()->forget('coupon');}$shipping=$state?app(ShippingService::class)->calculate($subtotal,$state)['amount']:15000.0;return[$items,$subtotal,$discount,$shipping,$subtotal-$discount+$shipping];}
 public function index(){if($this->cart()->isEmpty())return redirect()->route('cart')->with('error','Your cart is empty.');[$items,$subtotal,$discount,$shipping,$total]=$this->totals();$addresses=auth()->user()->addresses()->latest()->get();return view('shop.checkout',compact('items','subtotal','discount','shipping','total','addresses'));}
 public function applyCoupon(Request $r){$r->validate(['code'=>'required|string|max:50']);$items=$this->cart();$subtotal=(float)$items->sum(fn($i)=>$i['price']*$i['quantity']);$coupon=Coupon::where('code',strtoupper($r->code))->first();if(!$coupon||!$coupon->validFor($subtotal))return back()->with('error','That coupon is invalid or unavailable.');session(['coupon'=>$coupon->code]);return back()->with('success','Coupon applied.');}
 public function removeCoupon(){session()->forget('coupon');return back()->with('success','Coupon removed.');}
 public function place(Request $r,PaymentService $payments){$items=$this->cart();if($items->isEmpty())return redirect()->route('cart')->with('error','Your cart is empty.');$data=$r->validate(['name'=>'required|string|max:120','phone'=>'required|string|max:30','address'=>'required|string|max:255','city'=>'required|string|max:100','state'=>'required|string|max:100','notes'=>'nullable|string|max:1000','payment_method'=>'required|in:cod,paystack','save_address'=>'nullable|boolean']);[$items,$subtotal,$discount,$shipping,$total]=$this->totals($data['state']);$order=null;DB::transaction(function()use($data,$items,$subtotal,$discount,$shipping,$total,&$order){$order=Order::create(['user_id'=>auth()->id(),'number'=>'SH'.now()->format('ymd').strtoupper(Str::random(7)),'status'=>'pending','payment_method'=>$data['payment_method'],'payment_status'=>'pending','subtotal'=>$subtotal,'discount'=>$discount,'shipping'=>$shipping,'total'=>$total,'coupon_code'=>session('coupon'),'shipping_name'=>$data['name'],'shipping_phone'=>$data['phone'],'shipping_address'=>$data['address'],'shipping_city'=>$data['city'],'shipping_state'=>$data['state'],'notes'=>$data['notes']??null]);foreach($items as $id=>$item){$product=Product::whereKey($id)->lockForUpdate()->firstOrFail();if(!$product->status||$product->stock<$item['quantity'])abort(422,'A product in your cart is no longer available in the requested quantity.');$product->decrement('stock',$item['quantity']);$vendorId=$product->vendors()->value('vendors.id');$order->items()->create(['product_id'=>$product->id,'name'=>$product->name,'sku'=>$product->sku,'price'=>$item['price'],'quantity'=>$item['quantity'],'line_total'=>$item['price']*$item['quantity'],'vendor_id'=>$vendorId]);}if(session('coupon'))Coupon::where('code',session('coupon'))->increment('used_count');if($data['save_address']??false)Address::create(['user_id'=>auth()->id(),'label'=>'Saved address','name'=>$data['name'],'phone'=>$data['phone'],'address'=>$data['address'],'city'=>$data['city'],'state'=>$data['state'],'is_default'=>!Address::where('user_id',auth()->id())->exists()]);});session()->forget(['cart','coupon']);if($data['payment_method']==='paystack'){try{return redirect()->away($payments->initialize($order));}catch(RuntimeException $e){return redirect()->route('orders.show',$order)->with('error',$e->getMessage());}}return redirect()->route('orders.show',$order)->with('success','Order placed successfully.');}
 public function callback(Request $r,PaymentService $payments){$reference=$r->string('reference')->toString();$order=Order::where('number',$reference)->where('user_id',auth()->id())->firstOrFail();$verified=$payments->verify($reference);if($verified&&$verified->is($order))return redirect()->route('orders.show',$order)->with('success','Payment confirmed and your order is processing.');return redirect()->route('orders.show',$order)->with('error','Payment was not confirmed.');}
}
