<?php

namespace App\Http\Controllers;

use App\Models\{Dispute,GiftCard,LoyaltyAccount,LoyaltyTransaction,Order,PaymentTransaction,Product,ProductComparison,ProductQuestion,RecentlyViewedProduct,Refund,Vendor,VendorRating};
use App\Services\{PaymentService,VendorPayoutService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

class PlatformController extends Controller
{
    public function view(Product $product){RecentlyViewedProduct::updateOrCreate(['user_id'=>auth()->id(),'session_id'=>session()->getId(),'product_id'=>$product->id],['viewed_at'=>now()]);return redirect()->route('products.show',$product->slug);}
    public function compare(Product $product){ProductComparison::firstOrCreate(['user_id'=>auth()->id(),'session_id'=>session()->getId(),'product_id'=>$product->id]);return back()->with('success','Product added to comparison.');}
    public function comparisons(){return view('shop.compare',['products'=>ProductComparison::where('user_id',auth()->id())->with('product')->latest()->get()->pluck('product')]);}
    public function question(Request $request,Product $product){$data=$request->validate(['question'=>['required','string','max:2000']]);ProductQuestion::create($data+['product_id'=>$product->id,'user_id'=>auth()->id()]);return back()->with('success','Question submitted.');}
    public function dispute(Request $request){$data=$request->validate(['order_id'=>['required','integer','exists:orders,id'],'subject'=>['required','string','max:190'],'description'=>['required','string','max:5000']]);$order=Order::whereKey($data['order_id'])->where('user_id',auth()->id())->firstOrFail();abort_unless(in_array($order->status,['processing','shipped','delivered','cancelled','returned'],true),422,'This order cannot be disputed.');abort_if(Dispute::where('order_id',$order->id)->whereIn('status',['open','under_review'])->exists(),422,'An active dispute already exists for this order.');Dispute::create($data+['user_id'=>auth()->id(),'vendor_id'=>null,'status'=>'open']);return back()->with('success','Dispute opened.');}
    public function rateVendor(Request $request,Vendor $vendor){$data=$request->validate(['order_id'=>['required','integer','exists:orders,id'],'rating'=>['required','integer','min:1','max:5'],'comment'=>['nullable','string','max:2000']]);$purchased=DB::table('order_items')->join('orders','orders.id','=','order_items.order_id')->join('products','products.id','=','order_items.product_id')->where('orders.id',$data['order_id'])->where('orders.user_id',auth()->id())->where('products.vendor_id',$vendor->id)->exists();abort_unless($purchased,403,'You can only rate vendors for products you purchased.');VendorRating::updateOrCreate(['vendor_id'=>$vendor->id,'user_id'=>auth()->id(),'order_id'=>$data['order_id']],['rating'=>$data['rating'],'comment'=>$data['comment']??null]);return back()->with('success','Vendor rating saved.');}
    public function redeemPoints(Request $request){$data=$request->validate(['points'=>['required','integer','min:1']]);DB::transaction(function()use($data){$account=LoyaltyAccount::where('user_id',auth()->id())->lockForUpdate()->firstOrFail();abort_if($account->points<$data['points'],422,'Insufficient points.');$account->decrement('points',$data['points']);LoyaltyTransaction::create(['loyalty_account_id'=>$account->id,'points'=>-$data['points'],'type'=>'redeem','description'=>'Points redeemed']);});return back()->with('success','Points redeemed.');}
    public function buyGiftCard(Request $request){$data=$request->validate(['amount'=>['required','numeric','min:1000','max:1000000']]);$code='GFT-'.strtoupper(Str::random(12));GiftCard::create(['code'=>$code,'initial_value'=>$data['amount'],'balance'=>$data['amount'],'user_id'=>auth()->id()]);return back()->with('success','Gift card created: '.$code);}
    public function vendorApply(Request $request){$data=$request->validate(['business_name'=>['required','string','max:190'],'description'=>['nullable','string','max:3000'],'phone'=>['required','string','max:30'],'address'=>['required','string','max:255']]);abort_if(Vendor::where('user_id',auth()->id())->exists(),422,'Vendor application already exists.');Vendor::create($data+['user_id'=>auth()->id(),'slug'=>Str::slug($data['business_name']).'-'.Str::lower(Str::random(5)),'status'=>'pending','balance'=>0]);return back()->with('success','Vendor application submitted.');}
    public function vendorDashboard(){return view('vendor.dashboard',['v'=>Vendor::where('user_id',auth()->id())->where('status','approved')->firstOrFail()]);}
    public function vendorPayout(Request $request,VendorPayoutService $service){$vendor=Vendor::where('user_id',auth()->id())->where('status','approved')->firstOrFail();$data=$request->validate(['amount'=>['required','numeric','min:1000'],'bank_name'=>['required','string','max:100'],'account_number'=>['required','string','max:30'],'account_name'=>['required','string','max:190']]);try{$service->request($vendor,$data);}catch(RuntimeException $e){return back()->withErrors(['amount'=>$e->getMessage()]);}return back()->with('success','Payout request submitted for approval.');}
    public function webhook(Request $request,PaymentService $payments){$secret=config('services.paystack.secret');$signature=$request->header('x-paystack-signature');abort_unless($secret&&$signature&&hash_equals(hash_hmac('sha512',$request->getContent(),$secret),$signature),401);$data=$request->json('data',[]);$reference=$data['reference']??null;if($reference)$payments->confirmWebhook($reference,$data);return response()->json(['received'=>true]);}
    public function refund(Request $request,Order $order){abort_unless($order->user_id===auth()->id()||auth()->user()->isAdmin(),403);abort_unless($order->payment_status==='paid',422,'Only paid orders can be refunded.');$data=$request->validate(['amount'=>['required','numeric','min:0.01'],'reason'=>['nullable','string','max:1000']]);$already=Refund::where('order_id',$order->id)->whereIn('status',['requested','processed'])->sum('amount');abort_if($already+$data['amount']>$order->total,422,'Refund exceeds remaining refundable amount.');Refund::create(['order_id'=>$order->id,'user_id'=>$order->user_id,'amount'=>$data['amount'],'provider'=>$order->payment_method,'reference'=>'RF-'.strtoupper(Str::random(12)),'reason'=>$data['reason']??null,'status'=>'requested']);return back()->with('success','Refund request recorded.');}
    public function faq(){return view('shop.faq',['faqs'=>\App\Models\Faq::where('active',true)->orderBy('sort_order')->get()]);}
    public function analytics(){abort_unless(auth()->user()->isAdmin(),403);$days=collect(range(13,0))->map(fn($i)=>now()->subDays($i)->startOfDay());$sales=$days->map(fn($day)=>['date'=>$day->toDateString(),'revenue'=>Order::where('payment_status','paid')->whereBetween('created_at',[$day,$day->copy()->endOfDay()])->sum('total'),'orders'=>Order::whereBetween('created_at',[$day,$day->copy()->endOfDay()])->count()]);return view('admin.analytics',compact('sales'));}
}
